package:
  name: multinest
  version: "3.10"

source:
  path: ./

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - openmpi
    - lapack
    - openblas
    - openblas-devel
    - cmake
  run:
    - openmpi
    - lapack
    - openblas
    - openblas-devel

about:
  home: https://github.com/JohannesBuchner/MultiNest
  summary: "Shared library file for the MultiNest Nested Sampling engine."
